# -*- coding: utf-8 -*-
"""sentiment_analysis_DistilBERT.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1e4Zczm8ZX30Bih7sb4T_odm2PYjovp4w
"""

import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

!pip install wordcloud matplotlib

!pip install transformers

# load the csv file
df = pd.read_csv('feedback_data.csv', header=None)

df.head()

# Load pre-trained distilBERT model and tokenizer
from transformers import DistilBertTokenizer, DistilBertModel, pipeline # Corrected the typo in the module name from 'transofromers' to 'transformers'
model = DistilBertModel.from_pretrained('distilbert-base-uncased')
tokenizer = DistilBertTokenizer.from_pretrained('distilbert-base-uncased')

sentiment_analysis_bert = pipeline("sentiment-analysis", model = "nlptown/bert-base-multilingual-uncased-sentiment")

sentiment_results_bert = []

for index, row in df.iterrows():
    text = row[0]
    bert_result = sentiment_analysis_bert(text)[0]
    sentiment_label_bert = bert_result['label']
    sentiment_score_bert = bert_result['score']
    sentiment_results_bert.append({
        "Text":text,
        "Sentiment Score":sentiment_score_bert,
        "Sentiment label": sentiment_label_bert,
        })

for result in sentiment_results_bert:
    print(f"Text {result['Text']}")
    print(f"Sentiment Score {result['Sentiment Score']}")
    print(f"Sentiment Label {result['Sentiment label']}")

sentiment_df_bert = pd.DataFrame(sentiment_results_bert)

sentiment_df_bert.to_csv("sentiment_results.csv", index=False)

